[http]
  # this key is required even if it's empty
  [http.routers]

  [http.middlewares]
    [http.middlewares.admin-auth.basicAuth]
      users = ["admin:${admin_basic_auth_enrcypted_password}"]
    [http.middlewares.auth-gateway.forwardAuth]
      address = "${api_gateway_url}"
      authResponseHeaders = ["X-Smarta-Auth-Id","X-Smarta-Auth-Role","X-Smarta-Auth-Session","X-Smarta-Auth-Anonymous","X-Smarta-Auth-Superuser","X-Smarta-Auth-Issuer","X-Smarta-Auth-Phone","X-Smarta-Auth-Email"]
